//package com.tencent.mm;
//
//
//import com.tencent.mm.buildprop.BuildPropClass;
//import com.tencent.mm.buildprop.BuildPropKV;
//
//import java.io.BufferedReader;
//import java.io.ByteArrayInputStream;
//import java.io.IOException;
//import java.io.InputStreamReader;
//import java.nio.charset.Charset;
//import java.text.SimpleDateFormat;
//import java.util.ArrayList;
//import java.util.Calendar;
//import java.util.List;
//import java.util.Locale;
//
//public class Test {
//
//    private static String prop = "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a508\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "X3S\n" +
//            "X3S\n" +
//            "X3S\n" +
//            "v970\n" +
//            "zte\n" +
//            "zte\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "e510\n" +
//            "LG\n" +
//            "LG\n" +
//            "i8730\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "w680\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "honor\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "s610d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "i9305\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "m36h\n" +
//            "sony\n" +
//            "sony\n" +
//            "v889d\n" +
//            "zte\n" +
//            "zte\n" +
//            "evoview4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "e688\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "t329t\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a706\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "g525\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a1020\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "n788\n" +
//            "zte\n" +
//            "zte\n" +
//            "wildfire\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a800\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "a760\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "s6010l\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "v7\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "r801\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "c8500s\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "i9508\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "n9002\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "n881f\n" +
//            "zte\n" +
//            "zte\n" +
//            "p925\n" +
//            "LG\n" +
//            "LG\n" +
//            "a800\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "e455\n" +
//            "LG\n" +
//            "LG\n" +
//            "zme\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "zme\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "e780\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "v889s\n" +
//            "zte\n" +
//            "zte\n" +
//            "p2\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "me722\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "v7\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n881e\n" +
//            "zte\n" +
//            "zte\n" +
//            "n986\n" +
//            "zte\n" +
//            "zte\n" +
//            "ms770\n" +
//            "LG\n" +
//            "LG\n" +
//            "s5369\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "a366t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "lt25i\n" +
//            "sony\n" +
//            "sony\n" +
//            "xt711\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "s610d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "c8815\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "optimusg\n" +
//            "LG\n" +
//            "LG\n" +
//            "n1\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "lt30at\n" +
//            "sony\n" +
//            "sony\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s6012b\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "y500t\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "i9300\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "e621\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "mt620\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n788\n" +
//            "zte\n" +
//            "zte\n" +
//            "u8850\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "u985\n" +
//            "zte\n" +
//            "zte\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "188b\n" +
//            "LG\n" +
//            "LG\n" +
//            "s760\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "p705\n" +
//            "LG\n" +
//            "LG\n" +
//            "i659\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "v9\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "n960\n" +
//            "zte\n" +
//            "zte\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "f100\n" +
//            "LG\n" +
//            "LG\n" +
//            "n909\n" +
//            "zte\n" +
//            "zte\n" +
//            "e656\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "s560\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "s5369\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "w700\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "x905\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "st27i\n" +
//            "sony\n" +
//            "sony\n" +
//            "p920\n" +
//            "LG\n" +
//            "LG\n" +
//            "a218t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "i9100\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "z1\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "n790s\n" +
//            "zte\n" +
//            "zte\n" +
//            "mt720\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "s7562\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "a508\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "inspire4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "S7\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "u705t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "u705w\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "i939\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "t619plus\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "v9\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "s5830\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "st25i\n" +
//            "sony\n" +
//            "sony\n" +
//            "r813t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "r821t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "t703\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "d20082\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "t580\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "z1i\n" +
//            "sony\n" +
//            "sony\n" +
//            "milestone\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "s5838\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "y310\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "vision\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "n970\n" +
//            "zte\n" +
//            "zte\n" +
//            "t9199\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "su370\n" +
//            "LG\n" +
//            "LG\n" +
//            "a60\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "w3\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s7566\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "i9018\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "k1\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "r750\n" +
//            "zte\n" +
//            "zte\n" +
//            "onev\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "f120\n" +
//            "LG\n" +
//            "LG\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "a820\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "z1\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "Y15\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "r819t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "w760\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "v10\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "t8828\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "xt320\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u701\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "609d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "me632\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "w22\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "s5301\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "i9082\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "p940\n" +
//            "LG\n" +
//            "LG\n" +
//            "n780\n" +
//            "zte\n" +
//            "zte\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "t9199\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "e110s\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "sensationtd\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "u930hd\n" +
//            "zte\n" +
//            "zte\n" +
//            "y300\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "u9508\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "lu6200\n" +
//            "LG\n" +
//            "LG\n" +
//            "i899\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "sensationtd\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "X3\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "i9108\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "p6u06\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "ones\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "w806p\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "u20i\n" +
//            "sony\n" +
//            "sony\n" +
//            "mt27i\n" +
//            "sony\n" +
//            "sony\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "x907\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "p6c\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "salsa\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "i747\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "u9\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n1\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "y320u\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "u950\n" +
//            "zte\n" +
//            "zte\n" +
//            "h5018\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "v7mini\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "so04e\n" +
//            "sony\n" +
//            "sony\n" +
//            "v9\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "w6\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "v11t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "a369\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "X3\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "n798\n" +
//            "zte\n" +
//            "zte\n" +
//            "me525plus\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "a66\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "rezound\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "y210s\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "i437\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Y15\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n919\n" +
//            "zte\n" +
//            "zte\n" +
//            "a698t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "evo4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "X3\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "a790e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "w70\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "g610u\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "s6802\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "g525u\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "g525u\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a326\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "Xplay\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "s6802\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "w688\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "t329d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "raider4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "a310e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "xt907\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "e450\n" +
//            "LG\n" +
//            "LG\n" +
//            "evoview4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "lt30p\n" +
//            "sony\n" +
//            "sony\n" +
//            "xt901\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "v8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s870e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "i9100\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "r821t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "chacha\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a820\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "a390e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "i605\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "h5018\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s560\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "su640\n" +
//            "LG\n" +
//            "LG\n" +
//            "xt720\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "v965\n" +
//            "zte\n" +
//            "zte\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "s36h\n" +
//            "sony\n" +
//            "sony\n" +
//            "z1i\n" +
//            "sony\n" +
//            "sony\n" +
//            "xt910\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "p355\n" +
//            "LG\n" +
//            "LG\n" +
//            "u8\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a9188\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "e621\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "c988t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "p355\n" +
//            "LG\n" +
//            "LG\n" +
//            "p700i\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "y210s\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "e110s\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "u8\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "z560e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a65\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "vs920\n" +
//            "LG\n" +
//            "LG\n" +
//            "s5830i\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "a790e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "Y20\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n9002\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "c8500s\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a2109\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "v10\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "t8950n\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "w760\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "s820e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "t327d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "x909t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "u705t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "cliq2\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "Y15\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "e619\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a698t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "a66t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "mt620\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "flyer\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "xoom\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "s890\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "n8000\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "lepad\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "c966e\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "p925\n" +
//            "LG\n" +
//            "LG\n" +
//            "e210s\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "v881\n" +
//            "zte\n" +
//            "zte\n" +
//            "u808\n" +
//            "zte\n" +
//            "zte\n" +
//            "e619\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a850\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "e621\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "xt800plus\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "x909t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "xt532\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "aria\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a8i\n" +
//            "sony\n" +
//            "sony\n" +
//            "xt702\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "t93\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "lt28i\n" +
//            "sony\n" +
//            "sony\n" +
//            "ascend\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "st18i\n" +
//            "sony\n" +
//            "sony\n" +
//            "n986\n" +
//            "zte\n" +
//            "zte\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "w8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "t660\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "desirehd\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "xt316\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u705t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "a66t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "a9800\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "ascend\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "p3110\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "z3\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "w68\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "onev\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "u8661\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "x850\n" +
//            "zte\n" +
//            "zte\n" +
//            "w8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "u8800\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "u9000\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "xt711\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "a390\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "l39h\n" +
//            "sony\n" +
//            "sony\n" +
//            "a370\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "c8815\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "z3\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "r823t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "a366t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "mb525plus\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u8850\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "c1505\n" +
//            "sony\n" +
//            "sony\n" +
//            "6435lvw\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "n798\n" +
//            "zte\n" +
//            "zte\n" +
//            "v960\n" +
//            "zte\n" +
//            "zte\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "r530c\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "p940\n" +
//            "LG\n" +
//            "LG\n" +
//            "v987\n" +
//            "zte\n" +
//            "zte\n" +
//            "me722\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "lt22i\n" +
//            "sony\n" +
//            "sony\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "u9\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "g606t\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "v881\n" +
//            "zte\n" +
//            "zte\n" +
//            "so05d\n" +
//            "sony\n" +
//            "sony\n" +
//            "a706row\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "u8520\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "u795plus\n" +
//            "zte\n" +
//            "zte\n" +
//            "p705\n" +
//            "LG\n" +
//            "LG\n" +
//            "p713\n" +
//            "LG\n" +
//            "LG\n" +
//            "sk17i\n" +
//            "sony\n" +
//            "sony\n" +
//            "wt18i\n" +
//            "sony\n" +
//            "sony\n" +
//            "n9009\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "c8813q\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "a2109\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "milestone2\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u705t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "n980\n" +
//            "zte\n" +
//            "zte\n" +
//            "lt30at\n" +
//            "sony\n" +
//            "sony\n" +
//            "sgp312\n" +
//            "sony\n" +
//            "sony\n" +
//            "cliq2\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "me511\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "r821t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "a208t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "lt25c\n" +
//            "sony\n" +
//            "sony\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n600plus\n" +
//            "zte\n" +
//            "zte\n" +
//            "w6\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "i9300\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Y20\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "c966e\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "w719\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "p780\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "r817\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a9800t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "t329w\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "lt30p\n" +
//            "sony\n" +
//            "sony\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "u8160\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "c660\n" +
//            "LG\n" +
//            "LG\n" +
//            "f220\n" +
//            "LG\n" +
//            "LG\n" +
//            "so05d\n" +
//            "sony\n" +
//            "sony\n" +
//            "u8836d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "sk17i\n" +
//            "sony\n" +
//            "sony\n" +
//            "w7\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "w6\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "r807\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "x905\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "mb855\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "lt15i\n" +
//            "sony\n" +
//            "sony\n" +
//            "p715\n" +
//            "LG\n" +
//            "LG\n" +
//            "x10mini\n" +
//            "sony\n" +
//            "sony\n" +
//            "a390e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "me722\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "x907\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "u701t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "droid2global\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u809\n" +
//            "zte\n" +
//            "zte\n" +
//            "r811w\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "n700\n" +
//            "zte\n" +
//            "zte\n" +
//            "s5369\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Xplay\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "xt550\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "r821t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "w22\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "u790\n" +
//            "zte\n" +
//            "zte\n" +
//            "u9500\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "l39h\n" +
//            "sony\n" +
//            "sony\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "so03e\n" +
//            "sony\n" +
//            "sony\n" +
//            "s6802\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "n1t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "st25i\n" +
//            "sony\n" +
//            "sony\n" +
//            "a520\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "x907\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "u6\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "v8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "cliq2\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "s787\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "s715e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "p990\n" +
//            "LG\n" +
//            "LG\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "u8220\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "t8300\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a700e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "k1\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "r813t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "f160\n" +
//            "LG\n" +
//            "LG\n" +
//            "c666t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a398t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "u86\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "lt26w\n" +
//            "sony\n" +
//            "sony\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "f220\n" +
//            "LG\n" +
//            "LG\n" +
//            "u790\n" +
//            "zte\n" +
//            "zte\n" +
//            "milestone\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "r801\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "x907\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "mk16i\n" +
//            "sony\n" +
//            "sony\n" +
//            "r750\n" +
//            "zte\n" +
//            "zte\n" +
//            "mytouch4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "u791\n" +
//            "zte\n" +
//            "zte\n" +
//            "n795\n" +
//            "zte\n" +
//            "zte\n" +
//            "mb855\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "su540\n" +
//            "LG\n" +
//            "LG\n" +
//            "v11t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "802d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "c660t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "w3\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "r811\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "x850\n" +
//            "zte\n" +
//            "zte\n" +
//            "p990\n" +
//            "LG\n" +
//            "LG\n" +
//            "a798t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "c960t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "w95\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "Y20\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "e15i\n" +
//            "sony\n" +
//            "sony\n" +
//            "t96\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a390t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "mt720\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "c980t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "lt29i\n" +
//            "sony\n" +
//            "sony\n" +
//            "lu6200\n" +
//            "LG\n" +
//            "LG\n" +
//            "e971\n" +
//            "LG\n" +
//            "LG\n" +
//            "r817t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "lu6200\n" +
//            "LG\n" +
//            "LG\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "sk17i\n" +
//            "sony\n" +
//            "sony\n" +
//            "X3\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "a376\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "s787\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "s890\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "droidx\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "xt720\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "w710\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "u701\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a376\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "mb855\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "s36h\n" +
//            "sony\n" +
//            "sony\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "wt19i\n" +
//            "sony\n" +
//            "sony\n" +
//            "s6500d\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "n855\n" +
//            "zte\n" +
//            "zte\n" +
//            "w806p\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "p2\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "vision\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a9800\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "w8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "f240\n" +
//            "LG\n" +
//            "LG\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "r601\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "r817\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "u86\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "mt25i\n" +
//            "sony\n" +
//            "sony\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "z1\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "w700\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "v7mini\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "e210s\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a390\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "i589\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "t8500\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "mb200\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "p875\n" +
//            "LG\n" +
//            "LG\n" +
//            "a706row\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "i589\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "i9003\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "u701\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "v5t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "t9199\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "s850e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a9800\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "mb525\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "802t\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "v987\n" +
//            "zte\n" +
//            "zte\n" +
//            "608t\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "w808\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "mate\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "s5820\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "r823t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "ms770\n" +
//            "LG\n" +
//            "LG\n" +
//            "incredible\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "u807\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "u880f1\n" +
//            "zte\n" +
//            "zte\n" +
//            "f160l\n" +
//            "LG\n" +
//            "LG\n" +
//            "u793\n" +
//            "zte\n" +
//            "zte\n" +
//            "u950\n" +
//            "zte\n" +
//            "zte\n" +
//            "x909\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "k1\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "tattoo\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "w8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "r815t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "so03e\n" +
//            "sony\n" +
//            "sony\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "cliq2\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "p760\n" +
//            "LG\n" +
//            "LG\n" +
//            "n790\n" +
//            "zte\n" +
//            "zte\n" +
//            "u795plus\n" +
//            "zte\n" +
//            "zte\n" +
//            "a765e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "606w\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "c8650\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "p725\n" +
//            "LG\n" +
//            "LG\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "wt18i\n" +
//            "sony\n" +
//            "sony\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a590\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "v8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "t93\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "butterfly\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "f160s\n" +
//            "LG\n" +
//            "LG\n" +
//            "xt685\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "evo4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "wt19i\n" +
//            "sony\n" +
//            "sony\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "v5t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "x903\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "c980t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "s760\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "lt28i\n" +
//            "sony\n" +
//            "sony\n" +
//            "p350\n" +
//            "LG\n" +
//            "LG\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "f160s\n" +
//            "LG\n" +
//            "LG\n" +
//            "a66t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "b9062\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "p999\n" +
//            "LG\n" +
//            "LG\n" +
//            "s610d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "r801\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "mt27i\n" +
//            "sony\n" +
//            "sony\n" +
//            "s696\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "u956\n" +
//            "zte\n" +
//            "zte\n" +
//            "c8826d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "e110s\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "i8190l\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "evodesign4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "606w\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "r801t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "lighttab\n" +
//            "zte\n" +
//            "zte\n" +
//            "l39h\n" +
//            "sony\n" +
//            "sony\n" +
//            "u887\n" +
//            "zte\n" +
//            "zte\n" +
//            "d710\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "c988t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "xt720\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "a320e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "lt18i\n" +
//            "sony\n" +
//            "sony\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "e730\n" +
//            "LG\n" +
//            "LG\n" +
//            "s870e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "chacha\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "Xplay\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "a706row\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "e6\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a8i\n" +
//            "sony\n" +
//            "sony\n" +
//            "s5t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "l36h\n" +
//            "sony\n" +
//            "sony\n" +
//            "r823t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "t29\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "w6\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "xt615\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "mt15i\n" +
//            "sony\n" +
//            "sony\n" +
//            "n880\n" +
//            "zte\n" +
//            "zte\n" +
//            "v955\n" +
//            "zte\n" +
//            "zte\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "t619\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a1020\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "mb525plus\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "w650\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a218t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "u9000\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "x903\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "s6500d\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "w658\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "xt910\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "t660\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "c8800\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "i9100\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "S7\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n600plus\n" +
//            "zte\n" +
//            "zte\n" +
//            "mb886\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u20i\n" +
//            "sony\n" +
//            "sony\n" +
//            "Y15\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "n5120\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "sensation\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "lighttab\n" +
//            "zte\n" +
//            "zte\n" +
//            "droidx\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "w6\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "zme\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "mb855\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "n980\n" +
//            "zte\n" +
//            "zte\n" +
//            "i9228\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "u8950d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "X3\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "y310\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "lt28i\n" +
//            "sony\n" +
//            "sony\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "v791\n" +
//            "zte\n" +
//            "zte\n" +
//            "h5018\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "u8825d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "c960t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "i9003\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "x920e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "w22\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "802t\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "r811w\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "t96\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "st23i\n" +
//            "sony\n" +
//            "sony\n" +
//            "so03e\n" +
//            "sony\n" +
//            "sony\n" +
//            "c8813d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "b9388\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "s2005a\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "xt928\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "w8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s5300\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "x905\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "e450\n" +
//            "LG\n" +
//            "LG\n" +
//            "su370\n" +
//            "LG\n" +
//            "LG\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "i437\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "e730\n" +
//            "LG\n" +
//            "LG\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "incredible2\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "hero\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "st27i\n" +
//            "sony\n" +
//            "sony\n" +
//            "i8730\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "s39h\n" +
//            "sony\n" +
//            "sony\n" +
//            "wt18i\n" +
//            "sony\n" +
//            "sony\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "s7562i\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "n986\n" +
//            "zte\n" +
//            "zte\n" +
//            "n882e\n" +
//            "zte\n" +
//            "zte\n" +
//            "e510\n" +
//            "LG\n" +
//            "LG\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a8i\n" +
//            "sony\n" +
//            "sony\n" +
//            "i9210\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "e688\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "Y20\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "w808\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "e7\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "r813t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "s868t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "p350\n" +
//            "LG\n" +
//            "LG\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "a630\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "ones\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a9188\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "s820\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "f160l\n" +
//            "LG\n" +
//            "LG\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "evodesign4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "s870e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "v10\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "u8520\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "xt301\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "r803\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "r813t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "f160\n" +
//            "LG\n" +
//            "LG\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "su370\n" +
//            "LG\n" +
//            "LG\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "evoview4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "c660t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "i879\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "X3\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "mb525plus\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "p700\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "n780\n" +
//            "zte\n" +
//            "zte\n" +
//            "608t\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "t91\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "aria\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a630\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "s850e\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "i809\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "f260\n" +
//            "LG\n" +
//            "LG\n" +
//            "xt536\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u960s\n" +
//            "zte\n" +
//            "zte\n" +
//            "t528d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "t82\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "e120s\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "onex\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "e621\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "t81\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "a706\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "u8\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "a310e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "r815t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "w6\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s39h\n" +
//            "sony\n" +
//            "sony\n" +
//            "s560\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "st17i\n" +
//            "sony\n" +
//            "sony\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "xt800plus\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "i9100\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "188b\n" +
//            "LG\n" +
//            "LG\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "y320u\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "droid2global\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "S7\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "v9\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "e510\n" +
//            "LG\n" +
//            "LG\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "s6802\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "n983\n" +
//            "zte\n" +
//            "zte\n" +
//            "chacha\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "MX\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "Y20\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "xt316\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u8665\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "vs920\n" +
//            "LG\n" +
//            "LG\n" +
//            "r811\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "x903\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "v7mini\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "u817\n" +
//            "zte\n" +
//            "zte\n" +
//            "p895\n" +
//            "LG\n" +
//            "LG\n" +
//            "GalaxyNote2duos\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "sensation\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "i747\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Y15\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "i9505g\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "sk17i\n" +
//            "sony\n" +
//            "sony\n" +
//            "t8830\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a630t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "x907\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "mb525\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "n900\n" +
//            "zte\n" +
//            "zte\n" +
//            "me600\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "e730\n" +
//            "LG\n" +
//            "LG\n" +
//            "u8833\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "MX3\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "p350\n" +
//            "LG\n" +
//            "LG\n" +
//            "n8020\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "s6802\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "2A\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "z3\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "zme\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "v967s\n" +
//            "zte\n" +
//            "zte\n" +
//            "xt901\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "xt532\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "x903\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "z1i\n" +
//            "sony\n" +
//            "sony\n" +
//            "Xplay3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "a670t\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "lt29i\n" +
//            "sony\n" +
//            "sony\n" +
//            "u2\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "f200\n" +
//            "LG\n" +
//            "LG\n" +
//            "t789\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "v889s\n" +
//            "zte\n" +
//            "zte\n" +
//            "sensation4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "salsa\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "s7\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a706row\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "wt19i\n" +
//            "sony\n" +
//            "sony\n" +
//            "su640\n" +
//            "LG\n" +
//            "LG\n" +
//            "S9t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "t800\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "v8\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "t8500\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "c660t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "Mi3\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "amaze4g\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "g510\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "c988t\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "p500\n" +
//            "LG\n" +
//            "LG\n" +
//            "r821t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "t82\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "t96\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "u705w\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "Y20\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "i500\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "s7562\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "Y15\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "w7\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "f160s\n" +
//            "LG\n" +
//            "LG\n" +
//            "sc02c\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "w806\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "lu6800\n" +
//            "LG\n" +
//            "LG\n" +
//            "g606t\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a9800t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "s6012b\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "s717\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "mk16i\n" +
//            "sony\n" +
//            "sony\n" +
//            "r530u\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "s720\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "M8\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "MI2\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "c8826d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "Y11\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "a508\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "xt316\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "x10i\n" +
//            "sony\n" +
//            "sony\n" +
//            "c1605\n" +
//            "sony\n" +
//            "sony\n" +
//            "e612\n" +
//            "LG\n" +
//            "LG\n" +
//            "s720t\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "su540\n" +
//            "LG\n" +
//            "LG\n" +
//            "honor\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "c8812e\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "s5\n" +
//            "KTouch\n" +
//            "KTouch\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "f160s\n" +
//            "LG\n" +
//            "LG\n" +
//            "X3S\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "z510d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "n818\n" +
//            "zte\n" +
//            "zte\n" +
//            "h5018\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "i9018\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "u8818\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "s715e\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "a9800t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "v7\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "me811\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "u8220\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "d22010\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "st27i\n" +
//            "sony\n" +
//            "sony\n" +
//            "r819t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "MX2\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "t8951\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "a9188\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "M9\n" +
//            "meizu\n" +
//            "meizu\n" +
//            "n1t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "su540\n" +
//            "LG\n" +
//            "LG\n" +
//            "mb525\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "a706row\n" +
//            "lenovo\n" +
//            "lenovo\n" +
//            "Y19t\n" +
//            "vivo\n" +
//            "vivo\n" +
//            "su640\n" +
//            "LG\n" +
//            "LG\n" +
//            "t329d\n" +
//            "HTC\n" +
//            "HTC\n" +
//            "r801t\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "z3t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "xt702\n" +
//            "Moto\n" +
//            "Moto\n" +
//            "v955\n" +
//            "zte\n" +
//            "zte\n" +
//            "f120\n" +
//            "LG\n" +
//            "LG\n" +
//            "i8258\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "p713\n" +
//            "LG\n" +
//            "LG\n" +
//            "x850\n" +
//            "zte\n" +
//            "zte\n" +
//            "i9508\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "c1905\n" +
//            "sony\n" +
//            "sony\n" +
//            "c8826d\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "so04e\n" +
//            "sony\n" +
//            "sony\n" +
//            "t9510e\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "2S\n" +
//            "Xiaomi\n" +
//            "Xiaomi\n" +
//            "x907\n" +
//            "OPPO\n" +
//            "OPPO\n" +
//            "t8833\n" +
//            "huawei\n" +
//            "huawei\n" +
//            "v18t\n" +
//            "HONPhone\n" +
//            "HONPhone\n" +
//            "m250k\n" +
//            "samsung\n" +
//            "samsung\n" +
//            "i8190n\n" +
//            "samsung\n" +
//            "samsung";
//
//    private static String org = "\n" +
//            "# begin build properties\n" +
//            "# autogenerated by buildinfo.sh\n" +
//            "ro.build.id=M4B30Z\n" +
//            "ro.build.display.id=aosp_hammerhead-userdebug 6.0.1 M4B30Z eng.admin.20181119.175335 test-keys\n" +
//            "ro.build.version.incremental=eng.admin.20181119.175335\n" +
//            "ro.build.version.sdk=23\n" +
//            "ro.build.version.preview_sdk=0\n" +
//            "ro.build.version.codename=REL\n" +
//            "ro.build.version.all_codenames=REL\n" +
//            "ro.build.version.release=6.0.1\n" +
//            "ro.build.version.security_patch=2016-10-05\n" +
//            "ro.build.version.base_os=\n" +
//            "ro.build.date=Mon Nov 19 17:58:32 CST 2018\n" +
//            "ro.build.date.utc=1542621512\n" +
//            "ro.build.type=userdebug\n" +
//            "ro.build.user=admin\n" +
//            "ro.build.host=d-b4c0b5e7\n" +
//            "ro.build.tags=test-keys\n" +
//            "ro.build.flavor=aosp_hammerhead-userdebug\n" +
//            "ro.product.model=AOSP on HammerHead\n" +
//            "ro.product.brand=Android\n" +
//            "ro.product.name=aosp_hammerhead\n" +
//            "ro.product.device=hammerhead\n" +
//            "ro.product.board=hammerhead\n" +
//            "# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,\n" +
//            "# use ro.product.cpu.abilist instead.\n" +
//            "ro.product.cpu.abi=armeabi-v7a\n" +
//            "ro.product.cpu.abi2=armeabi\n" +
//            "ro.product.cpu.abilist=armeabi-v7a,armeabi\n" +
//            "ro.product.cpu.abilist32=armeabi-v7a,armeabi\n" +
//            "ro.product.cpu.abilist64=\n" +
//            "ro.product.manufacturer=LGE\n" +
//            "ro.product.locale=zh-CN\n" +
//            "ro.wifi.channels=\n" +
//            "ro.board.platform=msm8974\n" +
//            "# ro.build.product is obsolete; use ro.product.device\n" +
//            "ro.build.product=hammerhead\n" +
//            "# Do not try to parse description, fingerprint, or thumbprint\n" +
//            "ro.build.description=aosp_hammerhead-userdebug 6.0.1 M4B30Z eng.admin.20181119.175335 test-keys\n" +
//            "ro.build.fingerprint=Android/aosp_hammerhead/hammerhead:6.0.1/M4B30Z/admin11191754:userdebug/test-keys\n" +
//            "ro.build.characteristics=nosdcard\n" +
//            "# end build properties\n" +
//            "persist.sys.timezone=Asia/Shanghai\n" +
//            "\n" +
//            "#\n" +
//            "# ADDITIONAL_BUILD_PROPERTIES\n" +
//            "#\n" +
//            "keyguard.no_require_sim=true\n" +
//            "ro.com.android.dataroaming=true\n" +
//            "ro.config.ringtone=Ring_Synth_04.ogg\n" +
//            "ro.config.notification_sound=pixiedust.ogg\n" +
//            "ro.carrier=unknown\n" +
//            "ro.config.alarm_alert=Alarm_Classic.ogg\n" +
//            "ro.opengles.version=196608\n" +
//            "ro.sf.lcd_density=480\n" +
//            "persist.hwc.mdpcomp.enable=true\n" +
//            "ro.hwui.texture_cache_size=72\n" +
//            "ro.hwui.layer_cache_size=48\n" +
//            "ro.hwui.r_buffer_cache_size=8\n" +
//            "ro.hwui.path_cache_size=32\n" +
//            "ro.hwui.gradient_cache_size=1\n" +
//            "ro.hwui.drop_shadow_cache_size=6\n" +
//            "ro.hwui.texture_cache_flushrate=0.4\n" +
//            "ro.hwui.text_small_cache_width=1024\n" +
//            "ro.hwui.text_small_cache_height=1024\n" +
//            "ro.hwui.text_large_cache_width=2048\n" +
//            "ro.hwui.text_large_cache_height=1024\n" +
//            "drm.service.enabled=true\n" +
//            "ro.qti.sensors.max_geomag_rotv=60\n" +
//            "ro.qti.sensors.max_gyro_rate=200\n" +
//            "ro.qti.sensors.max_accel_rate=200\n" +
//            "ro.qti.sensors.max_grav=200\n" +
//            "ro.qti.sensors.max_rotvec=200\n" +
//            "ro.qti.sensors.max_orient=200\n" +
//            "ro.qti.sensors.max_linacc=200\n" +
//            "ro.qti.sensors.max_gamerv_rate=200\n" +
//            "ro.qti.sensors.smd=true\n" +
//            "ro.qti.sensors.game_rv=true\n" +
//            "ro.qti.sensors.georv=true\n" +
//            "ro.qti.sensors.smgr_mag_cal_en=true\n" +
//            "ro.qti.sensors.step_detector=true\n" +
//            "ro.qti.sensors.step_counter=true\n" +
//            "persist.debug.sensors.hal=w\n" +
//            "debug.qualcomm.sns.daemon=w\n" +
//            "debug.qualcomm.sns.libsensor1=w\n" +
//            "ro.telephony.call_ring.multiple=0\n" +
//            "wifi.interface=wlan0\n" +
//            "wifi.supplicant_scan_interval=15\n" +
//            "media.aac_51_output_enabled=true\n" +
//            "persist.radio.apm_sim_not_pwdn=1\n" +
//            "ro.telephony.default_network=10\n" +
//            "telephony.lteOnCdmaDevice=1\n" +
//            "persist.radio.mode_pref_nv10=1\n" +
//            "persist.radio.data_no_toggle=1\n" +
//            "persist.audio.handset.mic.type=digital\n" +
//            "persist.audio.dualmic.config=endfire\n" +
//            "persist.audio.fluence.voicecall=true\n" +
//            "persist.audio.fluence.voicecomm=true\n" +
//            "persist.audio.fluence.voicerec=false\n" +
//            "persist.audio.fluence.speaker=false\n" +
//            "ro.config.vc_call_vol_steps=6\n" +
//            "persist.radio.custom_ecc=1\n" +
//            "persist.radio.always_send_plmn=true\n" +
//            "ro.input.noresample=1\n" +
//            "af.fast_track_multiplier=1\n" +
//            "dalvik.vm.dex2oat-swap=false\n" +
//            "dalvik.vm.heapstartsize=8m\n" +
//            "dalvik.vm.heapgrowthlimit=192m\n" +
//            "dalvik.vm.heapsize=512m\n" +
//            "dalvik.vm.heaptargetutilization=0.75\n" +
//            "dalvik.vm.heapminfree=512k\n" +
//            "dalvik.vm.heapmaxfree=8m\n" +
//            "persist.sys.dalvik.vm.lib.2=libart\n" +
//            "dalvik.vm.isa.arm.variant=krait\n" +
//            "dalvik.vm.isa.arm.features=default\n" +
//            "dalvik.vm.lockprof.threshold=500\n" +
//            "net.bt.name=Android\n" +
//            "dalvik.vm.stack-trace-file=/data/anr/traces.txt\n" +
//            "ro.expect.recovery_id=0x9f395bfe55805eca951b3e363515b01930072fc9000000000000000000000000\n";
//
//
//    public static void main(String[] args){
//        System.out.println(modifyFile());
//    }
//
//
//    public static String modifyFile(){
//        List<BuildPropKV> buildPropKVList = new ArrayList<>();
//
//        //read
//        try {
//            BufferedReader br = new BufferedReader(new InputStreamReader(
//                    new ByteArrayInputStream(
//                            org.getBytes(Charset.forName("utf8"))), Charset.forName("utf8")));
//            String line;
//            while ( (line = br.readLine()) != null ) {
//                if(null != line && !line.equals("")){
//                    String[] keyValue = line.split("=");
//                    if(keyValue.length == 2){
//                        buildPropKVList.add(new BuildPropKV(keyValue[0],keyValue[1]));
//                    }else{
//                        buildPropKVList.add(new BuildPropKV(line,null));
//                    }
//                }else{
//                    buildPropKVList.add(new BuildPropKV("",null));
//                }
//            }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//
//        //display time
//        Calendar display_calendar = getRandomTime();
//        SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd.HHmmss", Locale.CHINA);
//        String display_time_str = format.format(display_calendar.getTime());
//
//        //build time
//        Calendar build_calendar = getRandomTime();
//        long build_timestamp = build_calendar.getTimeInMillis();
//        SimpleDateFormat build_format= new SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy", Locale.ENGLISH);
//        String build_time_str = build_format.format(build_calendar.getTime());
//
//        //fingerprint time
//        SimpleDateFormat fingerprint_format = new SimpleDateFormat("MMddHHmm", Locale.CHINA);
//        String fingerprint_time_str = fingerprint_format.format(display_calendar.getTime());
//
//        ArrayList<BuildPropClass> list = readAssert();
//        int randomIndex = (int)(Math.random()*list.size());
//        BuildPropClass buildProp = list.get(randomIndex);
//        String product = buildProp.product;
//        String company = buildProp.company;
//
//        String type = "user";
//        String tags = "release-keys";
//        String user_time = type+".admin."+display_time_str;
//        String flavor = product+"-"+type;
//        String display_id = flavor+" 6.0.1 M4B30Z "+user_time+" "+tags;
//        String buildId = company+" "+product;
//
//        modifyValue(buildPropKVList,"ro.build.id",buildId);
//        modifyValue(buildPropKVList,"ro.build.version.incremental",user_time);
//        modifyValue(buildPropKVList,"ro.build.date",build_time_str);
//        modifyValue(buildPropKVList,"ro.build.date.utc", (build_timestamp*1000+3228)+"");
//        modifyValue(buildPropKVList,"ro.build.type",type);
//        modifyValue(buildPropKVList,"ro.build.host","d-b440b6e7");
//        modifyValue(buildPropKVList,"ro.build.tags",tags);
//        modifyValue(buildPropKVList,"ro.build.flavor",flavor);
//        modifyValue(buildPropKVList,"ro.product.model",buildId);
//        modifyValue(buildPropKVList,"ro.product.name",product);
//        modifyValue(buildPropKVList,"ro.product.device",product);
//        modifyValue(buildPropKVList,"ro.product.board",product);
//        modifyValue(buildPropKVList,"ro.build.product",product);
//        modifyValue(buildPropKVList,"ro.build.display.id",display_id);
//        modifyValue(buildPropKVList,"ro.build.description",display_id);
//        modifyValue(buildPropKVList,"ro.build.fingerprint","Android/"+product+"/hammerhead:6.0.1/M4B30Z/admin"+fingerprint_time_str+":"+type+"/"+tags);
//        modifyValue(buildPropKVList,"ro.expect.recovery_id",create_recovery_id());
//        modifyValue(buildPropKVList,"ro.product.manufacturer",company);
//
//        //write
//        StringBuilder sb = new StringBuilder();
//        int size = buildPropKVList.size();
//        for(int i = 0; i < size; i ++ ){
//            BuildPropKV buildPropKV = buildPropKVList.get(i);
//            String key = buildPropKV.key;
//            String value = buildPropKV.value;
//            if(value != null){
//                sb.append(key+"="+value);
//                if(i!=size-1){
//                    sb.append("\n");
//                }
//            }else{
//                sb.append(key+"\n");
//            }
//        }
//
//        return  sb.toString();
//    }
//
//
//    private static void modifyValue(List<BuildPropKV> buildPropKVList,String key,String value){
//        for(BuildPropKV buildPropKV:buildPropKVList){
//            if(buildPropKV.key.equals(key)){
//                buildPropKV.value = value;
//                break;
//            }
//        }
//    }
//
//    private static String create_recovery_id(){
//        StringBuilder sb = new StringBuilder();
//        sb.append("0x");
//        char[] chars = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};
//        int size = chars.length;
//        for(int i = 0; i < 40; i ++ ){
//            char charItem = chars[(int) (Math.random() * size)];
//            sb.append(charItem);
//        }
//        sb.append("000000000000000000000000");
//        return sb.toString();
//    }
//
//    private static Calendar getRandomTime(){
//        Calendar calendar = Calendar.getInstance();
//        calendar.add(Calendar.YEAR,-1);
//        long display_time_start = calendar.getTimeInMillis();
//        calendar.add(Calendar.DAY_OF_MONTH,-4);
//        long display_time_end = calendar.getTimeInMillis();
//        long display_time = (long)(display_time_start+Math.random()*(display_time_end-display_time_start+1));
//        calendar.setTimeInMillis(display_time);
//        return calendar;
//    }
//
//
//    private static ArrayList<BuildPropClass> readAssert(){
//        ArrayList<BuildPropClass> list = new ArrayList<>();
//        try {
//            BufferedReader br = new BufferedReader(new InputStreamReader(
//                    new ByteArrayInputStream(
//                            prop.getBytes(Charset.forName("utf8"))), Charset.forName("utf8")));
//            String line;
//            while ((line = br.readLine()) != null) {
//                if(list.size() == 0){
//                    BuildPropClass buildProp = new BuildPropClass();
//                    list.add(buildProp);
//                }
//                BuildPropClass buildPropOld = list.get(list.size()-1);
//
//                if(buildPropOld.product == null){
//                    buildPropOld.product = line;
//                }else if(buildPropOld.company == null){
//                    buildPropOld.company = line;
//                }else if(buildPropOld.other == null){
//                    buildPropOld.other = line;
//                }else{
//                    BuildPropClass buildPropNew = new BuildPropClass();
//                    buildPropNew.product = line;
//                    list.add(buildPropNew);
//                }
//            }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//        return list;
//    }
//
//}
